import gzip

from bs4 import BeautifulSoup
from urllib.request import Request, urlopen


def url_object():
    data = []
    data.append(["https://coinmarketcap.com/it/currencies/bitcoin/", "priceValue", "Bitcoin", "BTC"])
    data.append(["https://coinmarketcap.com/it/currencies/ethereum/", "priceValue", "Ethereum", "ETH"])
    data.append(["https://coinmarketcap.com/it/currencies/tether/", "priceValue", "Tether", "USDT"])
    data.append(["https://coinmarketcap.com/it/currencies/cardano/", "priceValue", "Cardano", "ADA"])
    data.append(["https://coinmarketcap.com/it/currencies/polkadot-new/", "priceValue", "Polkadot", "DOT"])
    data.append(["https://coinmarketcap.com/it/currencies/xrp/", "priceValue", "XRP", "XRP"])
    data.append(["https://coinmarketcap.com/it/currencies/binance-coin/", "priceValue", "Binance Coin", "BNB"])
    data.append(["https://coinmarketcap.com/it/currencies/litecoin/", "priceValue", "Litecoin", "LTC"])
    data.append(["https://coinmarketcap.com/it/currencies/chainlink/", "priceValue", "Chainlink", "LINK"])
    data.append(["https://coinmarketcap.com/it/currencies/stellar/", "priceValue", "Stellar", "XLM"])
    data.append(["https://coinmarketcap.com/it/currencies/bitcoin-cash/", "priceValue", "Bitcoin Cash", "BCH"])
    data.append(["https://coinmarketcap.com/it/currencies/dogecoin/", "priceValue", "Dogecoin", "DOGE"])
    data.append(["https://coinmarketcap.com/it/currencies/uniswap/", "priceValue", "Uniswap", "UNI"])
    data.append(["https://coinmarketcap.com/it/currencies/usd-coin/", "priceValue", "USD Coin", "USDC"])
    data.append(["https://coinmarketcap.com/it/currencies/aave/", "priceValue", "Aave", "AAVE"])
    data.append(["https://coinmarketcap.com/it/currencies/wrapped-bitcoin/", "priceValue", "Wrapped Bitcoin", "WBTC"])
    data.append(["https://coinmarketcap.com/it/currencies/eos/", "priceValue", "EOS", "EOS"])
    data.append(["https://coinmarketcap.com/it/currencies/cosmos/", "priceValue", "Cosmos", "ATOM"])
    data.append(["https://coinmarketcap.com/it/currencies/bitcoin-sv/", "priceValue", "Bitcoin SV", "BSV"])
    data.append(["https://coinmarketcap.com/it/currencies/tron/", "priceValue", "TRON", "TRX"])
    data.append(["https://coinmarketcap.com/it/currencies/crypto-com-coin/", "priceValue", "Crypto.com Coin", "CRO"])
    data.append(["https://coinmarketcap.com/it/currencies/vechain/", "priceValue", "VeChain", "VET"])
    data.append(["https://coinmarketcap.com/it/currencies/the-sandbox/", "priceValue", "The Sandbox", "SAND"])
    data.append(["https://coinmarketcap.com/it/currencies/solana/", "priceValue", "Solana", "SOL"])
    data.append(["https://coinmarketcap.com/it/currencies/filecoin/", "priceValue", "Filecoin", "FIL"])
    data.append(["https://coinmarketcap.com/it/currencies/theta/", "priceValue", "THETA", "THETA"])
    data.append(["https://coinmarketcap.com/it/currencies/monero/", "priceValue", "Monero", "XMR"])
    data.append(["https://coinmarketcap.com/it/currencies/neo/", "priceValue", "Neo", "NEO"])
    data.append(["https://coinmarketcap.com/it/currencies/binance-usd/", "priceValue", "Binance USD", "BUSD"])
    data.append(["https://coinmarketcap.com/it/currencies/terra-luna/", "priceValue", "Terra Classic", "LUNC"])
    data.append(["https://coinmarketcap.com/it/currencies/klaytn/", "priceValue", "Klaytn", "KLAY"])
    data.append(["https://coinmarketcap.com/it/currencies/iota/", "priceValue", "IOTA", "MIOTA"])
    data.append(["https://coinmarketcap.com/it/currencies/bittorrent/", "priceValue", "BitTorrent", "BTT"])
    data.append(["https://coinmarketcap.com/it/currencies/pancakeswap/", "priceValue", "PancakeSwap", "CAKE"])
    data.append(["https://coinmarketcap.com/it/currencies/ftx-token/", "priceValue", "FTX Token", "FTT"])
    data.append(["https://coinmarketcap.com/it/currencies/maker/", "priceValue", "Maker", "MKR"])
    data.append(["https://coinmarketcap.com/it/currencies/multi-collateral-dai/", "priceValue", "Dai", "DAI"])
    data.append(["https://coinmarketcap.com/it/currencies/ethereum-classic/", "priceValue", "Ethereum Classic", "ETC"])
    data.append(["https://coinmarketcap.com/it/currencies/tezos/", "priceValue", "Tezos", "XTZ"])
    data.append(["https://coinmarketcap.com/it/currencies/algorand/", "priceValue", "Algorand", "ALGO"])
    data.append(["https://coinmarketcap.com/it/currencies/huobi-token/", "priceValue", "Huobi Token", "HT"])
    data.append(["https://coinmarketcap.com/it/currencies/avalanche/", "priceValue", "Avalanche", "AVAX"])
    data.append(["https://coinmarketcap.com/it/currencies/compound/", "priceValue", "Compound", "COMP"])
    data.append(["https://coinmarketcap.com/it/currencies/thorchain/", "priceValue", "THORChain", "RUNE"])
    data.append(["https://coinmarketcap.com/it/currencies/bitcoin-bep2/", "priceValue", "Bitcoin BEP2", "BTCB"])
    data.append(["https://coinmarketcap.com/it/currencies/kusama/", "priceValue", "Kusama", "KSM"])
    data.append(["https://coinmarketcap.com/it/currencies/elrond-egld/", "priceValue", "Elrond", "EGLD"])
    data.append(["https://coinmarketcap.com/it/currencies/dash/", "priceValue", "Dash", "DASH"])
    data.append(["https://coinmarketcap.com/it/currencies/nem/", "priceValue", "NEM", "XEM"])
    data.append(["https://coinmarketcap.com/it/currencies/zcash/", "priceValue", "Zcash", "ZEC"])
    data.append(["https://coinmarketcap.com/it/currencies/decred/", "priceValue", "Decred", "DCR"])
    data.append(["https://coinmarketcap.com/it/currencies/unus-sed-leo/", "priceValue", "UNUS SED LEO", "LEO"])
    data.append(["https://coinmarketcap.com/it/currencies/chiliz/", "priceValue", "Chiliz", "CHZ"])
    data.append(["https://coinmarketcap.com/it/currencies/holo/", "priceValue", "Holo", "HOT"])
    data.append(["https://coinmarketcap.com/it/currencies/stacks/", "priceValue", "Stacks", "STX"])
    data.append(["https://coinmarketcap.com/it/currencies/hedera-hashgraph/", "priceValue", "Hedera Hashgraph", "HBAR"])
    data.append(["https://coinmarketcap.com/it/currencies/terrausd/", "priceValue", "TerraUSD", "UST"])
    data.append(["https://coinmarketcap.com/it/currencies/nexo/", "priceValue", "Nexo", "NEXO"])
    data.append(["https://coinmarketcap.com/it/currencies/polygon/", "priceValue", "Polygon", "MATIC"])
    data.append(["https://coinmarketcap.com/it/currencies/decentraland/", "priceValue", "Decentraland", "MANA"])
    data.append(["https://coinmarketcap.com/it/currencies/enjin-coin/", "priceValue", "Enjin Coin", "ENJ"])
    data.append(["https://coinmarketcap.com/it/currencies/digibyte/", "priceValue", "DigiByte", "DGB"])
    data.append(["https://coinmarketcap.com/it/currencies/zilliqa/", "priceValue", "Zilliqa", "ZIL"])
    data.append(["https://coinmarketcap.com/it/currencies/basic-attention-token/", "priceValue", "Basic Attention Token", "BAT"])
    data.append(["https://coinmarketcap.com/it/currencies/the-graph/", "priceValue", "The Graph", "GRT"])
    data.append(["https://coinmarketcap.com/it/currencies/synthetix-network-token/", "priceValue", "Synthetix", "SNX"])
    data.append(["https://coinmarketcap.com/it/currencies/celsius/", "priceValue", "NEAR Protocol", "NEAR"])
    data.append(["https://coinmarketcap.com/it/currencies/siacoin/", "priceValue", "Siacoin", "SC"])
    data.append(["https://coinmarketcap.com/it/currencies/yearn-finance/", "priceValue", "yearn.finance", "YFI"])
    data.append(["https://coinmarketcap.com/it/currencies/bitcoin-gold/", "priceValue", "Bitcoin Gold", "BTG"])
    data.append(["https://coinmarketcap.com/it/currencies/waves/", "priceValue", "Waves", "WAVES"])
    data.append(["https://coinmarketcap.com/it/currencies/sushiswap/", "priceValue", "SushiSwap", "SUSHI"])
    data.append(["https://coinmarketcap.com/it/currencies/theta-fuel/", "priceValue", "Theta Fuel", "TFUEL"])
    data.append(["https://coinmarketcap.com/it/currencies/uma/", "priceValue", "UMA", "UMA"])
    data.append(["https://coinmarketcap.com/it/currencies/qtum/", "priceValue", "Qtum", "QTUM"])
    data.append(["https://coinmarketcap.com/it/currencies/ravencoin/", "priceValue", "Ravencoin", "RVN"])
    data.append(["https://coinmarketcap.com/it/currencies/horizen/", "priceValue", "Horizen", "ZEN"])
    data.append(["https://coinmarketcap.com/it/currencies/ontology/", "priceValue", "Ontology", "ONT"])
    data.append(["https://coinmarketcap.com/it/currencies/revain/", "priceValue", "Revain", "REV"])
    data.append(["https://coinmarketcap.com/it/currencies/0x/", "priceValue", "0x", "ZRX"])
    data.append(["https://coinmarketcap.com/it/currencies/bancor/", "priceValue", "Bancor", "BNT"])
    data.append(["https://coinmarketcap.com/it/currencies/helium/", "priceValue", "Helium", "HNT"])
    data.append(["https://coinmarketcap.com/it/currencies/swissborg/", "priceValue", "SwissBorg", "CHSB"])
    data.append(["https://coinmarketcap.com/it/currencies/icon/", "priceValue", "ICON", "ICX"])
    data.append(["https://coinmarketcap.com/it/currencies/celo/", "priceValue", "Celo", "CELO"])
    data.append(["https://coinmarketcap.com/it/currencies/nano/", "priceValue", "Nano", "NANO"])
    data.append(["https://coinmarketcap.com/it/currencies/okb/", "priceValue", "OKB", "OKB"])
    data.append(["https://coinmarketcap.com/it/currencies/harmony/", "priceValue", "Harmony", "ONE"])
    data.append(["https://coinmarketcap.com/it/currencies/reserve-rights/", "priceValue", "Reserve Rights", "RSR"])
    data.append(["https://coinmarketcap.com/it/currencies/flow/", "priceValue", "Flow", "FLOW"])
    data.append(["https://coinmarketcap.com/it/currencies/ankr/", "priceValue", "Ankr", "ANKR"])
    data.append(["https://coinmarketcap.com/it/currencies/paxos-standard/", "priceValue", "Paxos Standard", "PAX"])
    data.append(["https://coinmarketcap.com/it/currencies/omg/", "priceValue", "OMG Network", "OMG"])
    data.append(["https://coinmarketcap.com/it/currencies/kucoin-token/", "priceValue", "KuCoin Token", "KCS"])
    data.append(["https://coinmarketcap.com/it/currencies/iostoken/", "priceValue", "IOST", "IOST"])
    data.append(["https://coinmarketcap.com/it/currencies/ren/", "priceValue", "Ren", "REN"])
    data.append(["https://coinmarketcap.com/it/currencies/dent/", "priceValue", "Dent", "DENT"])
    data.append(["https://coinmarketcap.com/it/currencies/wazirx/", "priceValue", "WazirX", "WRX"])
    data.append(["https://coinmarketcap.com/it/currencies/fantom/", "priceValue", "Fantom", "FTM"])
    data.append(["https://coinmarketcap.com/it/currencies/voyager-token/", "priceValue", "Voyager Token", "VGX"])
    data.append(["https://coinmarketcap.com/it/currencies/shiba-inu/", "priceValue", "SHIBA INU", "SHIB"])
    data.append(["https://coinmarketcap.com/it/currencies/boson-protocol/", "priceValue", "Boson Protocol", "BOSON"])
    data.append(["https://coinmarketcap.com/it/currencies/efinity/", "priceValue", "Efinity Token", "EFI"])
    data.append(["https://coinmarketcap.com/it/currencies/axie-infinity/", "priceValue", "Axie Infinity", "AXS"])
    data.append(["https://coinmarketcap.com/it/currencies/terra-luna-v2/", "priceValue", "Terra", "LUNA"])
    data.append(["https://coinmarketcap.com/it/currencies/dydx/", "priceValue", "dYdX", "DYDX"])
    data.append(["https://coinmarketcap.com/it/currencies/cudos/", "priceValue", "CUDOS", "CUDOS"])
    data.append(["https://coinmarketcap.com/it/currencies/shiden-network/", "priceValue", "Shiden Network", "SDN"])
    data.append(["https://coinmarketcap.com/it/currencies/ethereum-pow/", "priceValue", "EthereumPow", "ETHW"])
    data.append(["https://coinmarketcap.com/it/currencies/merit-circle/", "priceValue", "Merit Circle", "MC"])
    '''data.append(["", "priceValue___11gHJ", "", ""])'''
    return data


def url_data(url):
    page = urlopen(url[0])
    check_type = page.info().get('content-encoding')
    if check_type == 'gzip':
        html = gzip.decompress(page.read()).decode('utf-8')
    else:
        html = page.read().decode("utf-8")
    soup = BeautifulSoup(html, "html.parser")
    data = soup.find("div", {"class": url[1]})
    return data